### PR TITLE
support going to the parent directory with backspace

### PR DESCRIPTION
**Pull request by alpheratz0**

### CODE REVIEW

**Comment by wael444** [comment]
what about da mouse buttons 9 and 8

**Comment by alpheratz0** [comment]
> what about da mouse buttons 9 and 8

1. I dont have such buttons
2. Mouse buttons 8 and 9 are used to move through the cwd history, and that's not what I am adding with this patch, I want to go to the parent directory, which may or may not be on the history

**Comment by wael444** [comment]
j

**Comment by phillbush** [comment]
Hi, @alpheratz0

This feature was removed from the C code and it is now handled by the controller script.

With the latest commit, XFiles now handles some keypresses with the controller script.

The "BackSpace" key now invokes the `xfilesctl ^BackSpace` command (key presses are identified by this `^` prefix), which uses `xprop(1)` to change XFiles' current working directory to `".."` (the parent directory).

That change was made to enable more modularity and configuration: Users can now do whatever they want on a keypress without the need to change the code; they just need to change the script.  For example, pressing "Delete" invokes `xfilesctl` to send files to trash; and pressing `Ctrl-L` invokes `xfilesctl`, which calls `dmenu` to act as a URL bar where you can type a directory to cd to.

In the end, a backspace still moves to the parent directory.

**Comment by wael444** [comment]
Is there any reason why using a simple config.h file isn't preferred over this weird way?

**Comment by phillbush** [comment]
> Is there any reason why using a simple config.h file isn't preferred over this weird way?

I think using shell script for extending functionality is better than extending it in the source code.
That does not require the user to know C, for example.
And in the end, what would be added to a `config.h` would be a command to exec with `sh`.

For example, I could add `Ctrl-C` and `Ctrl-V` functionality in the [last commit](https://github.com/phillbush/xfiles/commit/4c377464fabfa839b4d7ebb1788427f098ad9a8a) without any change to the code, just by changing the `xfilesctl` script.

Opening `dmenu` to type a directory to change to could also be implemented on the script.

**Comment by phillbush** [comment]
Btw, sorry about all the forced pushes.
Git is still untamed to me.

**Pull request merged**
