### PR TITLE
Add vi keybinds

### PR DESCRIPTION
**Pull request by 20mattia02**
h, j, k, l = move around
shift + h = go to upper dir
shift + l = open file

### CODE REVIEW

**Review by alpheratz0 — COMMENTED** [review]
Hi @20mattia02!

Nice work, but you also need to edit `xfiles.1` and document those new keybindings.

**Comment by 20mattia02** [comment]
Done, altough there's probably a better way to put it.

**Comment by phillbush** [comment]
Hi, @20mattia02

I have other plans for the keys producing letters (and other printable characters).

I will implement a type-to-search feature that will highlight the first file whose name contains the string typed in the keyboard.

This is what the other file managers I have tested (xfe and pcmanfm) do, and I think it's a nice feature to implement on XFiles.

So the h/j/k/l keys will be used for searching, not selecting like arrow keys.

However, If this type-to-search feature needs way more work than I'm willing to do (which can be the case, if it needs to handle input context), then I can use H/J/K/L for moving.

**Comment by 20mattia02** [comment]
Hi, @phillbush 

with respect I think that is a questionable decision. It wastes many keys which would otherwise be available to other functions and it could lead to unwanted searches caused by unintentional key presses.

Not to mention that there are many many users who are used to the vi keybinds, which would be kinda left out.

Ofc it's your program and you decide, but my proposal would be to have a dedicated key for the search feature (e.g. '/').

**Pull request merged**
