### PR TITLE
config.c: fix thumbnailing

### PR DESCRIPTION
**Pull request by wael444**
solves https://github.com/phillbush/xfiles/issues/26

### CODE REVIEW

**Comment by wael444** [comment]
lol

**Comment by wael444** [comment]
shit it gives the same error wtf

**Comment by wael444** [comment]
oh

**Comment by wael444** [comment]
i mean this should still be merged cuz it fixes the command itself atleast

**Comment by phillbush** [comment]
> i mean this should still be merged cuz it fixes the command itself atleast

The command is not wrong.
The `[0]` at the end of the input filename is interpreted by ImageMagick's `convert(1)`  to use the first image data in the file; for example, the first frame in a `.gif` or the first subfile in a `.tiff`.

**Comment by wael444** [comment]
well the thumbnailing still fails sooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

maybe do that for *.gif files, or that can also be possible for video files which can remove the ffmpegthumbnailer dependency.
better yet, use ffmpeg directly for all thumbnailing.

**Comment by phillbush** [comment]
> well the thumbnailing still fails

What error message does it show?.
And which version of ImageMagick/`convert` are you using?

> maybe do that for *.gif files

The `[0]` suffix is be ignored for other file formats, like png.  It is innocuous, therefore.

> or that can also be possible for video files which can remove the ffmpegthumbnailer dependency.

Although ImageMagick's `convert` works for taking a frame from a video; it was not made exactly for that.
`ffmpegthumbnailer` is faster for that job, which is desirable for bulk-generating thumbnails on a directory full of videos.

>  better yet, use ffmpeg directly for all thumbnailing.

`ffmpeg` does not work on files without video/audio stream, such as images.

**Comment by wael444** [comment]
> What error message does it show?.

#26 

> And which version of ImageMagick/convert are you using?
```
Version: ImageMagick 7.1.0-51 Q16-HDRI x86_64 20499 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib fontconfig freetype jng jpeg lzma pangocairo png tiff webp x xml zlib
Compiler: gcc (12.2)
```

> "ffmpegthumbnailer is faster for that job"
> C++
> just a library wrapper for ffmpeg

> ffmpeg does not work on files without video/audio stream, such as images.

you didn't try!

**Comment by phillbush** [comment]
My version of ImageMagick is 6.9.
The 7.X version have not been ported to my system yet.

Much stuff have changed between those major versions.
That may be the reason why it is working for me but not for you.

I can replace the dependency on ImageMagick to [netpbm](https://netpbm.sourceforge.net/) or [farbfeld](https://tools.suckless.org/farbfeld/), which are simpler, faster, and suck less (and theyr interfaces are way less prone to change between versions).

**Comment by phillbush** [comment]
ImageMagick is no more.
Using netpbm now, as it is the simplest and most compatible utility to use with XFiles.

**Pull request closed without merging**
